### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by felenitaribeiro** [NeuroDesk/play.neurodesk.org#1]
Not sure if this repo is the best place for this issue, but when I create a conda environment without setting a specific Python version, like in 'conda create -n myenv,' this env doesn't get listed on the 'Select Kernel' dropdown menu on a Jupyter Notebook, and no new Icon for launching a Jupyter notebook with that environment activated shows up. It seems like it only works as it should when I set a specific Python version and install packages

**Comment by stebo85** [comment]
that's good to know! I will test and check

**Comment by stebo85** [comment]
problem is that every environment needs at least a kernel, so ipykernel, or r-irkernel

Idea: Add documentation and make clear that a kernel is required (and document for which language):

#create a python environment" 
conda create -n myenv ipykernel

#create R environment:
conda create -n r_env r-irkernel

**Comment by stebo85** [comment]
and add that if forgotten: conda install ipykernel (not pip install ipykernel)

**Comment by stebo85** [comment]
I now documented this in the new image in a Readme. We should document this on the website once Thuy completed the reorganisation of the website.

**Comment by felenitaribeiro** [comment]
I will wait for her to make my pull request with the conda tutorial
